// Two-stage build: the build script first generates a header with values it computed itself, then
// compiles a program that includes it and runs it. This is how version strings, build timestamps or
// feature flags get into a binary without hardcoding them in the sources.
#define CB_IMPLEMENTATION
#define CB_ENABLE_ECHO
#include "cb.h"

#define OUT_FOLDER "./build/examples/03_two_stage/"
#define CONFIG_PATH OUT_FOLDER "config.h"
#define SRC_PATH OUT_FOLDER "main.c"
#define BIN_PATH OUT_FOLDER "two_stage"

static const char* source =
    "#include <stdio.h>\n"
    "#include \"config.h\"\n"
    "int main(void)\n"
    "{\n"
    "    printf(\"name = %s\\n\", APP_NAME);\n"
    "    printf(\"max jobs = %d\\n\", APP_MAX_JOBS);\n"
    "    return 0;\n"
    "}\n";

bool generate_config(void)
{
    // Built at run time: the header therefore differs on a machine with a different core count.
    CB_String_Builder sb = CB_ZERO;
    cb_sb_appendf(&sb, "// Generated by examples/03_two_stage.c, do not edit.\n");
    cb_sb_appendf(&sb, "#define APP_NAME \"two-stage build\"\n");
    cb_sb_appendf(&sb, "#define APP_MAX_JOBS %d\n", cb_nprocs());

    // items is always NUL-terminated, so count bytes are exactly the text without the terminator.
    bool ok = cb_write_entire_file(CONFIG_PATH, sb.items, sb.count);
    cb_sb_free(sb);
    return ok;
}

int main(void)
{
    cb_minimal_log_level = CB_INFO;

    if (!cb_mkdir_if_not_exists(OUT_FOLDER)) return 1;
    if (!generate_config()) return 1;
    if (!cb_write_entire_file(SRC_PATH, source, strlen(source))) return 1;

    // Stage two: the generated header is just another input of the compile step.
    CB_Cmd cmd = CB_ZERO;
    cb_cc(&cmd);
    cb_cc_flags(&cmd);
    cb_cmd_append(&cmd, cb_temp_sprintf("-I%s", OUT_FOLDER));
    cb_cc_output(&cmd, BIN_PATH);
    cb_cc_inputs(&cmd, SRC_PATH);
    if (!cb_cmd_run(&cmd)) return 1;

    cb_cmd_append(&cmd, BIN_PATH);
    if (!cb_cmd_run(&cmd)) return 1;

    free(cmd.items);
    return 0;
}
